export enum AlertStatuses {
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  ERROR = "ERROR",
  INFO = "INFO",
}

export enum AlertPosition {
  TOP = "TOP",
  TOP_START = "TOP_START",
  TOP_END = "TOP_END",
  MIDDLE = "MIDDLE",
  MIDDLE_START = "MIDDLE_START",
  MIDDLE_END = "MIDDLE_END",
  BOTTOM = "BOTTOM",
  BOTTOM_START = "BOTTOM_START",
  BOTTOM_END = "BOTTOM_END",
}
