export { Head } from "./Head";
export {
  DefaultSeo,
  NextSeo,
  NextSeoProps,
  ArticleJsonLd,
  BreadcrumbJsonLd,
  FAQPageJsonLd,
  JobPostingJsonLd,
  BlogJsonLd,
  CourseJsonLd,
  DatasetJsonLd,
  LocalBusinessJsonLd,
  LogoJsonLd,
  ProductJsonLd,
  SocialProfileJsonLd,
  CorporateContactJsonLd,
  NewsArticleJsonLd,
  EventJsonLd,
  VideoJsonLd,
  QAPageJsonld,
  RecipeJsonLd,
  VideoGameJsonLd,
  CarouselJsonLd,
  SiteLinksSearchBoxJsonLd,
  SoftwareAppJsonLd,
  CollectionPageJsonLd,
  ProfilePageJsonLd,
} from "next-seo";
