import { FAVOURITE_TYPES } from "@constants";

export const posts = [
  {
    _id: 1,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "123",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 2,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 3,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 4,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 5,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 6,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
];

export const favouriteArtists = [
  {
    name: "Soen",
    slug: "soen",
    image: "/images/favourites/soen.png",
    category: "rock-metal",
  },
  {
    name: "Muse",
    slug: "muse",
    image: "/images/favourites/muse.png",
    category: "rock-metal",
  },
  {
    name: "Radiohead",
    slug: "radiohead",
    image: "/images/favourites/radiohead.jpeg",
    category: "rock-metal",
  },
  {
    name: "Marilyn Manson",
    slug: "marilyn-manson",
    image: "/images/favourites/marilyn-manson.jpg",
    category: "rock-metal",
  },
  {
    name: "Metallica",
    slug: "Metallica",
    image: "/images/favourites/metallica.png",
    category: "rock-metal",
  },
  {
    name: "Mohsen Chavoshi",
    slug: "mohsen-chavoshi",
    image: "/images/favourites/mohsen-chavoshi.jpeg",
    category: "other",
  },
  {
    name: "Empyrium",
    slug: "empyrium",
    image: "/images/favourites/empyrium.jpg",
    category: "rock-metal",
  },
  {
    name: "Uaral",
    slug: "uaral",
    image: "/images/favourites/uaral.jpg",
    category: "rock-metal",
  },
  {
    name: "Nirvana",
    slug: "nirvana",
    image: "/images/favourites/nirvana.jpg",
    category: "rock-metal",
  },

  {
    name: "Opeth",
    slug: "opeth",
    image: "/images/favourites/opeth.jpg",
    category: "rock-metal",
  },
  {
    name: "Tool",
    slug: "tool",
    image: "/images/favourites/tool.jpg",
    category: "rock-metal",
  },
  {
    name: "Linkin Park",
    slug: "linkin-park",
    image: "/images/favourites/linkin-park.jpg",
    category: "rock-metal",
  },
  {
    name: "Slipknot",
    slug: "slipknot",
    image: "/images/favourites/slipknot.jpg",
    category: "rock-metal",
  },
  {
    name: "System of A Down",
    slug: "system-of-a-down",
    image: "/images/favourites/system-of-a-down.jpg",
    category: "rock-metal",
  },
  {
    name: "Avenged Sevenfold",
    slug: "avenged-sevenfold",
    image: "/images/favourites/avenged-sevenfold.jpg",
    category: "rock-metal",
  },
  {
    name: "Cigarettes After Sex",
    slug: "cigarettes-after-sex",
    image: "/images/favourites/cigarettes-after-sex.jpg",
    category: "other",
  },
  {
    name: "Hozier",
    slug: "hozier",
    image: "/images/favourites/hozier.jpg",
    category: "other",
  },
  {
    name: "Frank Ocean",
    slug: "frank-ocean",
    image: "/images/favourites/frank-ocean.jpg",
    category: "other",
  },
];

export const favouritePlaylists = [
  {
    name: "Best of Soen",
    slug: "soen",
    image: "/images/favourites/soen.png",
    tracks: [
      { name: "Martyrs", artist: "Soen" },
      { name: "Lotus", artist: "Soen" },
      { name: "Illusion", artist: "Soen" },
      { name: "Pluton", artist: "Soen" },
      { name: "The Words", artist: "Soen" },
      { name: "Lunacy", artist: "Soen" },
      { name: "Monarch", artist: "Soen" },
      { name: "Lucidity", artist: "Soen" },
      { name: "Penance", artist: "Soen" },
      { name: "River", artist: "Soen" },
      { name: "Void", artist: "Soen" },
      { name: "Lascivious", artist: "Soen" },
      { name: "Lumerian", artist: "Soen" },
      { name: "Paragon", artist: "Soen" },
      { name: "Rival", artist: "Soen" },
      { name: "Fortune", artist: "Soen" },
      { name: "Savia", artist: "Soen" },
      { name: "Antagonist", artist: "Soen" },

      // { name: "Modesty", artist: "Soen" },
      // { name: "Dissident", artist: "Soen" },
      // { name: "Orison", artist: "Soen" },
      // { name: "Golds Acre", artist: "Soen" },
      // { name: "Opponent", artist: "Soen" },
      // { name: "Opal", artist: "Soen" },
      // { name: "Covenant", artist: "Soen" },
      // { name: "Last Night", artist: "Soen" },
    ],
  },
  {
    name: "Best of Muse",
    slug: "muse",
    image: "/images/favourites/muse.png",
    tracks: [
      { name: "Hysteria", artist: "Muse" },
      { name: "Starlight", artist: "Muse" },
      { name: "Sunburn", artist: "Muse" },
      { name: "Citizen Erased", artist: "Muse" },
      { name: "Uprising", artist: "Muse" },
      { name: "The Second Law Isolated System", artist: "Muse" },
      { name: "Sing For Absolution", artist: "Muse" },
      { name: "Plug In Baby", artist: "Muse" },
      { name: "Apocalypse Please", artist: "Muse" },
      { name: "Stockholm Syndrome", artist: "Muse" },
      { name: "Assassin", artist: "Muse" },
      { name: "Supermassive Black Hole", artist: "Muse" },
      { name: "Undisclosed Desire", artist: "Muse" },
      { name: "Knights Of Cydonia", artist: "Muse" },
      { name: "Butterflies and Hurricanes", artist: "Muse" },
      { name: "Unintended", artist: "Muse" },
      { name: "United States of Eurasia", artist: "Muse" },
      { name: "Endlessly", artist: "Muse" },
      { name: "Map Of The Problematique", artist: "Muse" },
      { name: "Psycho", artist: "Muse" },
      { name: "Dig Down", artist: "Muse" },
      { name: "Animals", artist: "Muse" },
      { name: "Hyper Music", artist: "Muse" },
      { name: "Resistance", artist: "Muse" },
    ],
  },
  {
    name: "Best of Radiohead",
    slug: "radiohead",
    image: "/images/favourites/radiohead.jpeg",
    tracks: [
      { name: "Creep", artist: "Radiohead" },
      { name: "Nude", artist: "Radiohead" },
      { name: "Three, Three", artist: "Radiohead" },
      { name: "Exit Music", artist: "Radiohead" },
      { name: "How to disappear Completely", artist: "Radiohead" },
      { name: "Fake Plastic Trees", artist: "Radiohead" },
      { name: "Paranoid Android", artist: "Radiohead" },
      { name: "My Iron Lung", artist: "Radiohead" },
      { name: "High and Dry", artist: "Radiohead" },
      { name: "I Promise", artist: "Radiohead" },
      { name: "Climbing up the Walls", artist: "Radiohead" },
      { name: "Bishop's Robes", artist: "Radiohead" },
      { name: "No Surprises", artist: "Radiohead" },
      { name: "Subterranean Homesick Alien", artist: "Radiohead" },
      { name: "Street Spirit (Fade Out)", artist: "Radiohead" },
      { name: "Sail to the Moon", artist: "Radiohead" },
    ],
  },
  {
    name: "Best of Marilyn Manson",
    slug: "marilyn-manson",
    image: "/images/favourites/marilyn-manson.jpg",
    tracks: [
      { name: "Running on the Edge of The World", artist: "Marilyn Manson" },
      { name: "Just A Car Crash Away", artist: "Marilyn Manson" },
      {
        name: "In The Shadow of the Valley of Death",
        artist: "Marilyn Manson",
      },
      { name: "Coma White", artist: "Marilyn Manson" },
      { name: "Unkillable Monster", artist: "Marilyn Manson" },
      { name: "If I was Your Vampire", artist: "Marilyn Manson" },
      { name: "The End", artist: "Marilyn Manson" },
      { name: "Into the Fire", artist: "Marilyn Manson" },
      { name: "Sweet Dreams", artist: "Marilyn Manson" },
      { name: "Lamb of God", artist: "Marilyn Manson" },
      { name: "Don't Chase the Dead", artist: "Marilyn Manson" },
      { name: "We Are Chaos", artist: "Marilyn Manson" },
      { name: "Red Black and Blue", artist: "Marilyn Manson" },
      { name: "Cry Little Sister", artist: "Marilyn Manson" },
      { name: "Beautiful People", artist: "Marilyn Manson" },
      { name: "Warship My Wreck", artist: "Marilyn Manson" },
      { name: "Paint You With My Love", artist: "Marilyn Manson" },
      { name: "One Step Forward", artist: "Marilyn Manson" },
      { name: "Coma Black", artist: "Marilyn Manson" },
      { name: "Tainted Love", artist: "Marilyn Manson" },
    ],
  },
  // {
  //   name: "Best of Metallica",
  //   slug: "metallica",
  //   image: "/images/favourites/metallica.png",
  //   tracks: [
  //     { name: "Mama Said", artist: "Metallica" },
  //     { name: "Mama Said", artist: "Metallica" },
  //     { name: "Mama Said", artist: "Metallica" },
  //   ],
  // },
  {
    name: "Best of Mohsen Chavoshi",
    slug: "mohsen-chavoshi",
    image: "/images/favourites/mohsen-chavoshi.jpeg",
    tracks: [
      { name: "Sange Sabour", artist: "Mohsen Chavoshi" },
      { name: "Rahe Doshvar", artist: "Mohsen Chavoshi" },
      { name: "Parvaneh ha", artist: "Mohsen Chavoshi" },
      { name: "Boofe Koor", artist: "Mohsen Chavoshi" },
      { name: "Ghomarbaz", artist: "Mohsen Chavoshi" },
      { name: "Changiz", artist: "Mohsen Chavoshi" },
      { name: "Amir Bi Gazand", artist: "Mohsen Chavoshi" },
      { name: "Khouzestan", artist: "Mohsen Chavoshi" },

      { name: "Paroye Bi Ghayegh", artist: "Mohsen Chavoshi" },
      { name: "Dore Akhar", artist: "Mohsen Chavoshi" },

      { name: "Setamgar", artist: "Mohsen Chavoshi" },
      { name: "Chang", artist: "Mohsen Chavoshi" },

      { name: "Taghe Soraya", artist: "Mohsen Chavoshi" },
      { name: "Hasrate Khis", artist: "Mohsen Chavoshi" },

      { name: "Raaz", artist: "Mohsen Chavoshi" },

      { name: "Mahi Kenare Rood", artist: "Mohsen Chavoshi" },
      { name: "Divare Bi Dar", artist: "Mohsen Chavoshi" },

      { name: "Hamkhab", artist: "Mohsen Chavoshi" },
      { name: "Maleka", artist: "Mohsen Chavoshi" },

      { name: "Kalagh", artist: "Mohsen Chavoshi" },
      { name: "Har Rouz Paeize", artist: "Mohsen Chavoshi" },
      { name: "Afsar", artist: "Mohsen Chavoshi" },
      { name: "Maslakh", artist: "Mohsen Chavoshi" },

      { name: ". . ." },

      // { name: "Ghatar", artist: "Mohsen Chavoshi" },
      // { name: "Gonjeshke Parideh", artist: "Mohsen Chavoshi" },
      // { name: "Man Nadanestam", artist: "Mohsen Chavoshi" },
      // { name: "Shabi Ke Mah Kamel Shod", artist: "Mohsen Chavoshi" },

      // { name: "Tanha Boudan", artist: "Mohsen Chavoshi" },
      // { name: "Dar Astaneye Piri", artist: "Mohsen Chavoshi" },
      // { name: "Jahane Fasede Mardom Ra", artist: "Mohsen Chavoshi" },
      // { name: "Kalanjar", artist: "Mohsen Chavoshi" },
      // { name: "Douset Dashtam", artist: "Mohsen Chavoshi" },
      // { name: "Nashkan Delamo", artist: "Mohsen Chavoshi" },
      // { name: "Lebase No", artist: "Mohsen Chavoshi" },
      // { name: "Zahed", artist: "Mohsen Chavoshi" },
      // { name: "Deltangi", artist: "Mohsen Chavoshi" },
      // { name: "Naaz", artist: "Mohsen Chavoshi" },
      // { name: "Desire", artist: "Mohsen Chavoshi" },
    ],
  },
];

export const favouriteBooks = [
  // name: "", fullName: "", image: "", writer: "Charles Duhigg",
  "the-power-of-habit",
  "the-unbearable-lightness-of-being",
  "masnavi",
  "quran",
  "golestan",
  "nahj-al-balagha",
  "tafsir-nemooneh",
  "republic",
];

export const favouriteMovies = [
  "forrest-gump",
  "santoori",
  "the-shawshank-redemption",
  "the-lord-of-the-rings",
  "star-wars",
  "toy-story",
];

export const favouriteSeries = [
  "the-office",
  "the-big-bang-theory",
  "friends",
  "vikings",
  "mind-hunter",
  "avatar-the-last-airbender",
  "the-leng-of-korra",
  "rick-and-morty",
  "scenes-from-a-marriage",
  "true-detective",
  "its-always-aunny-in-philadelphia",
  "boJack-horseman",
  "family-guy",
  "fleabag",
  "shameless",
  "big-little-lies",
  "horace-and-pete",
];

export const favouriteAnime = [
  "spirited-away",
  "princess-mononoke",
  "fullmetal-alchemist-brotherhood",
  "death-note",
  "attack-on-titan",
  "ghost-in-the-shell",
  "hunter-x-hunter",
  "steins-gate",
  "berserk",
  "demon-slayer",
];

export const favourites = {
  [FAVOURITE_TYPES.SONG.ARTISTS]: favouriteArtists,
  [FAVOURITE_TYPES.SONG.PLAYLISTS]: favouritePlaylists,
};

export const blogs = [
  {
    _id: 1,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "slug-1",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 2,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-2",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 3,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-3",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 4,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-4",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 5,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-5",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 6,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-6",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 7,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "slug-7",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 8,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-8",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 9,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-9",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 10,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-10",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 11,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-11",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 12,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-12",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
];

export const projectsData = {
  en: [
    {
      _id: 0,
      name: "Octava",
      link: "https://www.octava.ir",
      logo: "/images/projects/octava/logo.png",
      medias: [
        { src: "/images/projects/octava/desktop/1.png" },
        { src: "/images/projects/octava/desktop/2.png" },
        { src: "/images/projects/octava/pwa/1.png" },
        // prettier-ignore
        { src: "/images/projects/octava/pwa/2.png", title: "projects.octava.points.9" },
        { src: "/images/projects/octava/desktop/3.png" },
        { src: "/images/projects/octava/pwa/3.png" },
        { src: "/images/projects/octava/desktop/4.png" },
        { src: "/images/projects/octava/desktop/1-skeleton.png" },
        // prettier-ignore
        { src: "/images/projects/octava/desktop/1-blur.png", title: "projects.octava.points.7" },
        { src: "/images/projects/octava/desktop/5.png" },
        // prettier-ignore
        { src: "/images/projects/octava/pwa/4.png", title: "projects.octava.points.9" },
        { src: "/images/projects/octava/pwa/5.png" },
        { src: "/images/projects/octava/desktop/6.png" },
        // prettier-ignore
        { src: "/images/projects/octava/pwa/6.png", title: "projects.octava.points.9" },
        { src: "/images/projects/octava/desktop/7.png" },
        { src: "/images/projects/octava/pwa/7.png" },
        { src: "/images/projects/octava/desktop/8.png" },
        { src: "/images/projects/octava/pwa/8.png" },
        { src: "/images/projects/octava/pwa/8-skeleton.png" },
        // prettier-ignore
        { src: "/images/projects/octava/desktop/5-skeleton.png" },
        { src: "/images/projects/octava/pwa/1-skeleton.png" },
      ],
      date: "",
      slug: "octava",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        { name: "Next.js", link: "https://www.npmjs.com/package/next" },
        { name: "swr", link: "https://www.npmjs.com/package/swr" },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        {
          name: "socket.io-client",
          link: "https://www.npmjs.com/package/socket.io-client",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
      ],
      description: "Persian music streaming platform",
      points: [
        "projects.octava.points.1",
        {
          title: "projects.octava.points.2",
          points: [
            "projects.octava.points.2-1",
            "projects.octava.points.2-2",
            "projects.octava.points.2-3",
            {
              title: "projects.octava.points.2-4",
              points: [
                "projects.octava.points.2-4-1",
                "projects.octava.points.2-4-2",
                "projects.octava.points.2-4-3",
                "projects.octava.points.2-4-4",
              ],
            },
          ],
        },
        {
          title: "projects.octava.points.3",
          points: [
            "projects.octava.points.3-1",
            "projects.octava.points.3-2",
            "projects.octava.points.3-3",
            "projects.octava.points.3-4",
          ],
        },
        "projects.octava.points.4",
        {
          title: "projects.octava.points.5",
          points: [
            "projects.octava.points.5-1",
            "projects.octava.points.5-2",
            "projects.octava.points.5-3",
          ],
        },
        {
          title: "projects.octava.points.6",
          points: [
            "projects.octava.points.6-1",
            "projects.octava.points.6-2",
            "projects.octava.points.6-3",
          ],
        },
        {
          title: "projects.octava.points.7",
          points: [
            "projects.octava.points.7-1",
            "projects.octava.points.7-2",
            "projects.octava.points.7-3",
          ],
        },
        "projects.octava.points.8",
        "projects.octava.points.9",
      ],
    },
    {
      _id: 1,
      name: "Uneed",
      link: ["https://www.uneed.ir", "https://www.merchant.uneed.ir"],
      logo: "/images/projects/uneed/logo.png",
      medias: [
        { src: "/images/projects/uneed/desktop/1.png", title: "image 1" },
        { src: "/images/projects/uneed/desktop/2.png", title: "image 2" },
        { src: "/images/projects/uneed/desktop/3.png", title: "image 3" },
        { src: "/images/projects/uneed/desktop/4.png", title: "image 4" },
        { src: "/images/projects/uneed/desktop/5.png", title: "image 5" },
        { src: "/images/projects/uneed/desktop/6.png", title: "image 6" },
        { src: "/images/projects/uneed/desktop/7.png", title: "image 7" },
        { src: "/images/projects/uneed/desktop/8.png", title: "image 8" },
        { src: "/images/projects/uneed/desktop/9.png", title: "image 9" },
        { src: "/images/projects/uneed/mobile/1.png", title: "image 1" },
      ],
      date: "2020",
      slug: "uneed",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        { name: "Next.js", link: "https://www.npmjs.com/package/next" },
        {
          name: "Redux Saga",
          link: "https://www.npmjs.com/package/redux-saga",
        },
        { name: "express", link: "https://www.npmjs.com/package/next-seo" },
        {
          name: "socket.io-client",
          link: "https://www.npmjs.com/package/socket.io-client",
        },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
      ],
      description:
        "A platform for free posting of advertisements and inquiries regarding the purchase and sale of new and used products.",
      points: [
        "projects.uneed.points.1",
        "projects.uneed.points.2",
        "projects.uneed.points.3",
        "projects.uneed.points.4",
      ],
    },
    {
      _id: 2,
      name: "Tarinoo",
      link: [
        "https://www.tarinoo.ir",
        "https://www.zarco.ir",
        "https://www.lapert.ir",
        "https://risu.ir",
        "...",
      ],
      logo: "/images/projects/tarinoo/logo.jpeg",
      medias: [
        { src: "/images/projects/tarinoo/1.png", title: "image 1" },
        { src: "/images/projects/tarinoo/2.png", title: "image 2" },
        { src: "/images/projects/tarinoo/3.png", title: "image 3" },
        { src: "/images/projects/tarinoo/4.png", title: "image 4" },
        { src: "/images/projects/tarinoo/5.png", title: "image 5" },
        { src: "/images/projects/tarinoo/6.png", title: "image 6" },
        { src: "/images/projects/tarinoo/7.png", title: "image 7" },
        { src: "/images/projects/tarinoo/8.png", title: "image 8" },
        { src: "/images/projects/tarinoo/9.png", title: "image 9" },
        { src: "/images/projects/tarinoo/10.png", title: "image 10" },
        { src: "/images/projects/tarinoo/11.png", title: "image 11" },
      ],
      date: "2020",
      slug: "tarinoo",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        { name: "Next.js", link: "https://www.npmjs.com/package/next" },
        {
          name: "Redux Saga",
          link: "https://www.npmjs.com/package/redux-saga",
        },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
      ],
      description:
        "Another product of uneed infrastructure, built to sell fully customized websites to business-type users",
      points: ["projects.tarinoo.points.1", "projects.tarinoo.points.2"],
    },
    {
      _id: 3,
      name: "Bityon",
      link: "",
      logo: "/images/projects/bityon/logo.png",
      medias: [
        { src: "/images/projects/bityon/desktop/1.png", title: "image 1" },
        { src: "/images/projects/bityon/desktop/2.png", title: "image 2" },
        { src: "/images/projects/bityon/desktop/3.png", title: "image 3" },
        { src: "/images/projects/bityon/desktop/4.png", title: "image 4" },
        { src: "/images/projects/bityon/desktop/5.png", title: "image 5" },
        { src: "/images/projects/bityon/desktop/6.png", title: "image 6" },
        { src: "/images/projects/bityon/desktop/7.png", title: "image 7" },
        { src: "/images/projects/bityon/mobile/1.png", title: "image 1" },
        { src: "/images/projects/bityon/mobile/2.png", title: "image 2" },
        { src: "/images/projects/bityon/mobile/3.png", title: "image 3" },
        { src: "/images/projects/bityon/mobile/4.png", title: "image 4" },
      ],
      date: "",
      slug: "bityon",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        { name: "Next.js", link: "https://www.npmjs.com/package/next" },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
        {
          name: "highcharts",
          link: "https://www.npmjs.com/package/highcharts",
        },
      ],
      description:
        "A secure platform to buy and sell bitcoin and other crypto currencies.",
      points: [
        {
          title: "projects.bityon.points.1",
          points: [
            "projects.bityon.points.1-1",
            "projects.bityon.points.1-2",
            "projects.bityon.points.1-3",
            "projects.bityon.points.1-4",
          ],
        },
      ],
    },
    {
      _id: 4,
      name: "BIZ",
      link: "https://www.bizmlm.ir",
      logo: "/images/projects/biz/logo.png",
      medias: [
        { src: "/images/projects/biz/1.png", title: "image 1" },
        { src: "/images/projects/biz/2.png", title: "image 2" },
        { src: "/images/projects/biz/3.png", title: "image 3" },
        { src: "/images/projects/biz/4.png", title: "image 4" },
        { src: "/images/projects/biz/5.png", title: "image 5" },
        { src: "/images/projects/biz/6.png", title: "image 6" },
        { src: "/images/projects/biz/7.png", title: "image 7" },
        { src: "/images/projects/biz/8.png", title: "image 8" },
      ],
      date: "",
      slug: "biz",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        {
          name: "socket.io-client",
          link: "https://www.npmjs.com/package/socket.io-client",
        },
        { name: "Express", link: "https://www.npmjs.com/package/express" },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
      ],
      description: "The biggest iranian network marketing company.",
      points: [
        {
          title: "projects.biz.points.1",
          points: [
            "projects.biz.points.2-1",
            "projects.biz.points.2-2",
            "projects.biz.points.2-3",
          ],
        },
        "projects.biz.points.3",
        "projects.biz.points.4",
      ],
    },
    {
      _id: 5,
      name: "CRM Panel",
      link: "https://www.crm.ir",
      logo: "/images/projects/crm/logo.png",
      medias: [
        { src: "/images/projects/crm/1.png", title: "image 1" },
        { src: "/images/projects/crm/2.png", title: "image 2" },
        { src: "/images/projects/crm/3.png", title: "image 3" },
        { src: "/images/projects/crm/4.png", title: "image 4" },
      ],
      date: "",
      slug: "crm",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        {
          name: "socket.io-client",
          link: "https://www.npmjs.com/package/socket.io-client",
        },
        { name: "React Query", link: "https://www.npmjs.com/package/next-seo" },
        {
          name: "Styled Components",
          link: "https://www.npmjs.com/package/styled-components",
        },
        { name: "i18next", link: "https://www.npmjs.com/package/i18next" },
      ],
      description:
        "Customer relationship management panel that provides an all-in-one social media management tool.",
      points: [
        {
          title: "projects.crm.points.1",
          points: ["projects.crm.points.1-1", "projects.crm.points.1-2"],
        },
        "projects.crm.points.2",
        "projects.crm.points.3",
      ],
    },
    {
      _id: 6,
      name: "And so forth ...",
      logo: "/images/projects/etc.png",
      data: "2018-present",
      description: "Projects that I'm not really proud of ( ^_^;)",
      slug: "etc",
      techs: [
        { name: "React", link: "https://www.npmjs.com/package/react" },
        {
          name: "React-native",
          link: "https://www.npmjs.com/package/next-seo",
        },
        { name: "Angular", link: "https://www.npmjs.com/package/next-seo" },
        { name: "wordpress", link: "https://www.npmjs.com/package/next-seo" },
      ],
    },
  ],
};
