import { FAVOURITE_TYPES } from "@constants";

export const posts = [
  {
    _id: 1,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "123",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 2,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 3,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 4,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 5,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 6,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
];

export const favouriteArtists = [
  {
    name: "Soen",
    slug: "soen",
    image: "/images/favourites/soen.png",
    category: "rock-metal",
  },
  {
    name: "Muse",
    slug: "muse",
    image: "/images/favourites/muse.png",
    category: "rock-metal",
  },
  {
    name: "Radiohead",
    slug: "radiohead",
    image: "/images/favourites/radiohead.jpeg",
    category: "rock-metal",
  },
  {
    name: "Marilyn Manson",
    slug: "marilyn-manson",
    image: "/images/favourites/marilyn-manson.jpg",
    category: "rock-metal",
  },
  {
    name: "Metallica",
    slug: "Metallica",
    image: "/images/favourites/metallica.png",
    category: "rock-metal",
  },
  {
    name: "Mohsen Chavoshi",
    slug: "mohsen-chavoshi",
    image: "/images/favourites/mohsen-chavoshi.jpeg",
    category: "other",
  },
  {
    name: "Empyrium",
    slug: "empyrium",
    image: "/images/favourites/empyrium.jpg",
    category: "rock-metal",
  },
  {
    name: "Uaral",
    slug: "uaral",
    image: "/images/favourites/uaral.jpg",
    category: "rock-metal",
  },
  {
    name: "Nirvana",
    slug: "nirvana",
    image: "/images/favourites/nirvana.jpg",
    category: "rock-metal",
  },

  {
    name: "Opeth",
    slug: "opeth",
    image: "/images/favourites/opeth.jpg",
    category: "rock-metal",
  },
  {
    name: "Tool",
    slug: "tool",
    image: "/images/favourites/tool.jpg",
    category: "rock-metal",
  },
  {
    name: "Linkin Park",
    slug: "linkin-park",
    image: "/images/favourites/linkin-park.jpg",
    category: "rock-metal",
  },
  {
    name: "Slipknot",
    slug: "slipknot",
    image: "/images/favourites/slipknot.jpg",
    category: "rock-metal",
  },
  {
    name: "System of A Down",
    slug: "system-of-a-down",
    image: "/images/favourites/system-of-a-down.jpg",
    category: "rock-metal",
  },
  {
    name: "Avenged Sevenfold",
    slug: "avenged-sevenfold",
    image: "/images/favourites/avenged-sevenfold.jpg",
    category: "rock-metal",
  },
  {
    name: "Cigarettes After Sex",
    slug: "cigarettes-after-sex",
    image: "/images/favourites/cigarettes-after-sex.jpg",
    category: "other",
  },
  {
    name: "Hozier",
    slug: "hozier",
    image: "/images/favourites/hozier.jpg",
    category: "other",
  },
  {
    name: "Frank Ocean",
    slug: "frank-ocean",
    image: "/images/favourites/frank-ocean.jpg",
    category: "other",
  },
];

export const favouritePlaylists = [
  {
    name: "Best of Soen",
    slug: "soen",
    image: "/images/favourites/soen.png",
    tracks: [
      { name: "Martyrs", artist: "Soen" },
      { name: "Lotus", artist: "Soen" },
      { name: "Illusion", artist: "Soen" },
      { name: "Pluton", artist: "Soen" },
      { name: "The Words", artist: "Soen" },
      { name: "Lunacy", artist: "Soen" },
      { name: "Monarch", artist: "Soen" },
      { name: "Lucidity", artist: "Soen" },
      { name: "Penance", artist: "Soen" },
      { name: "River", artist: "Soen" },
      { name: "Void", artist: "Soen" },
      { name: "Lascivious", artist: "Soen" },
      { name: "Lumerian", artist: "Soen" },
      { name: "Paragon", artist: "Soen" },
      { name: "Rival", artist: "Soen" },
      { name: "Fortune", artist: "Soen" },
      { name: "Savia", artist: "Soen" },
      { name: "Antagonist", artist: "Soen" },

      // { name: "Modesty", artist: "Soen" },
      // { name: "Dissident", artist: "Soen" },
      // { name: "Orison", artist: "Soen" },
      // { name: "Golds Acre", artist: "Soen" },
      // { name: "Opponent", artist: "Soen" },
      // { name: "Opal", artist: "Soen" },
      // { name: "Covenant", artist: "Soen" },
      // { name: "Last Night", artist: "Soen" },
    ],
  },
  {
    name: "Best of Muse",
    slug: "muse",
    image: "/images/favourites/muse.png",
    tracks: [
      { name: "Hysteria", artist: "Muse" },
      { name: "Starlight", artist: "Muse" },
      { name: "Sunburn", artist: "Muse" },
      { name: "Citizen Erased", artist: "Muse" },
      { name: "Uprising", artist: "Muse" },
      { name: "The Second Law Isolated System", artist: "Muse" },
      { name: "Sing For Absolution", artist: "Muse" },
      { name: "Plug In Baby", artist: "Muse" },
      { name: "Apocalypse Please", artist: "Muse" },
      { name: "Stockholm Syndrome", artist: "Muse" },
      { name: "Assassin", artist: "Muse" },
      { name: "Supermassive Black Hole", artist: "Muse" },
      { name: "Undisclosed Desire", artist: "Muse" },
      { name: "Knights Of Cydonia", artist: "Muse" },
      { name: "Butterflies and Hurricanes", artist: "Muse" },
      { name: "Unintended", artist: "Muse" },
      { name: "United States of Eurasia", artist: "Muse" },
      { name: "Endlessly", artist: "Muse" },
      { name: "Map Of The Problematique", artist: "Muse" },
      { name: "Psycho", artist: "Muse" },
      { name: "Dig Down", artist: "Muse" },
      { name: "Animals", artist: "Muse" },
      { name: "Hyper Music", artist: "Muse" },
      { name: "Resistance", artist: "Muse" },
    ],
  },
  {
    name: "Best of Radiohead",
    slug: "radiohead",
    image: "/images/favourites/radiohead.jpeg",
    tracks: [
      { name: "Creep", artist: "Radiohead" },
      { name: "Nude", artist: "Radiohead" },
      { name: "Three, Three", artist: "Radiohead" },
      { name: "Exit Music", artist: "Radiohead" },
      { name: "How to disappear Completely", artist: "Radiohead" },
      { name: "Fake Plastic Trees", artist: "Radiohead" },
      { name: "Paranoid Android", artist: "Radiohead" },
      { name: "My Iron Lung", artist: "Radiohead" },
      { name: "High and Dry", artist: "Radiohead" },
      { name: "I Promise", artist: "Radiohead" },
      { name: "Climbing up the Walls", artist: "Radiohead" },
      { name: "Bishop's Robes", artist: "Radiohead" },
      { name: "No Surprises", artist: "Radiohead" },
      { name: "Subterranean Homesick Alien", artist: "Radiohead" },
      { name: "Street Spirit (Fade Out)", artist: "Radiohead" },
      { name: "Sail to the Moon", artist: "Radiohead" },
    ],
  },
  {
    name: "Best of Marilyn Manson",
    slug: "marilyn-manson",
    image: "/images/favourites/marilyn-manson.jpg",
    tracks: [
      { name: "Running on the Edge of The World", artist: "Marilyn Manson" },
      { name: "Just A Car Crash Away", artist: "Marilyn Manson" },
      {
        name: "In The Shadow of the Valley of Death",
        artist: "Marilyn Manson",
      },
      { name: "Coma White", artist: "Marilyn Manson" },
      { name: "Unkillable Monster", artist: "Marilyn Manson" },
      { name: "If I was Your Vampire", artist: "Marilyn Manson" },
      { name: "The End", artist: "Marilyn Manson" },
      { name: "Into the Fire", artist: "Marilyn Manson" },
      { name: "Sweet Dreams", artist: "Marilyn Manson" },
      { name: "Lamb of God", artist: "Marilyn Manson" },
      { name: "Don't Chase the Dead", artist: "Marilyn Manson" },
      { name: "We Are Chaos", artist: "Marilyn Manson" },
      { name: "Red Black and Blue", artist: "Marilyn Manson" },
      { name: "Cry Little Sister", artist: "Marilyn Manson" },
      { name: "Beautiful People", artist: "Marilyn Manson" },
      { name: "Warship My Wreck", artist: "Marilyn Manson" },
      { name: "Paint You With My Love", artist: "Marilyn Manson" },
      { name: "One Step Forward", artist: "Marilyn Manson" },
      { name: "Coma Black", artist: "Marilyn Manson" },
      { name: "Tainted Love", artist: "Marilyn Manson" },
    ],
  },
  // {
  //   name: "Best of Metallica",
  //   slug: "metallica",
  //   image: "/images/favourites/metallica.png",
  //   tracks: [
  //     { name: "Mama Said", artist: "Metallica" },
  //     { name: "Mama Said", artist: "Metallica" },
  //     { name: "Mama Said", artist: "Metallica" },
  //   ],
  // },
  {
    name: "Best of Mohsen Chavoshi",
    slug: "mohsen-chavoshi",
    image: "/images/favourites/mohsen-chavoshi.jpeg",
    tracks: [
      { name: "Sange Sabour", artist: "Mohsen Chavoshi" },
      { name: "Rahe Doshvar", artist: "Mohsen Chavoshi" },
      { name: "Parvaneh ha", artist: "Mohsen Chavoshi" },
      { name: "Boofe Koor", artist: "Mohsen Chavoshi" },
      { name: "Ghomarbaz", artist: "Mohsen Chavoshi" },
      { name: "Changiz", artist: "Mohsen Chavoshi" },
      { name: "Amir Bi Gazand", artist: "Mohsen Chavoshi" },
      { name: "Khouzestan", artist: "Mohsen Chavoshi" },

      { name: "Paroye Bi Ghayegh", artist: "Mohsen Chavoshi" },
      { name: "Dore Akhar", artist: "Mohsen Chavoshi" },

      { name: "Setamgar", artist: "Mohsen Chavoshi" },
      { name: "Chang", artist: "Mohsen Chavoshi" },

      { name: "Taghe Soraya", artist: "Mohsen Chavoshi" },
      { name: "Hasrate Khis", artist: "Mohsen Chavoshi" },

      { name: "Raaz", artist: "Mohsen Chavoshi" },

      { name: "Mahi Kenare Rood", artist: "Mohsen Chavoshi" },
      { name: "Divare Bi Dar", artist: "Mohsen Chavoshi" },

      { name: "Hamkhab", artist: "Mohsen Chavoshi" },
      { name: "Maleka", artist: "Mohsen Chavoshi" },

      { name: "Kalagh", artist: "Mohsen Chavoshi" },
      { name: "Har Rouz Paeize", artist: "Mohsen Chavoshi" },
      { name: "Afsar", artist: "Mohsen Chavoshi" },
      { name: "Maslakh", artist: "Mohsen Chavoshi" },

      { name: ". . ." },

      // { name: "Ghatar", artist: "Mohsen Chavoshi" },
      // { name: "Gonjeshke Parideh", artist: "Mohsen Chavoshi" },
      // { name: "Man Nadanestam", artist: "Mohsen Chavoshi" },
      // { name: "Shabi Ke Mah Kamel Shod", artist: "Mohsen Chavoshi" },

      // { name: "Tanha Boudan", artist: "Mohsen Chavoshi" },
      // { name: "Dar Astaneye Piri", artist: "Mohsen Chavoshi" },
      // { name: "Jahane Fasede Mardom Ra", artist: "Mohsen Chavoshi" },
      // { name: "Kalanjar", artist: "Mohsen Chavoshi" },
      // { name: "Douset Dashtam", artist: "Mohsen Chavoshi" },
      // { name: "Nashkan Delamo", artist: "Mohsen Chavoshi" },
      // { name: "Lebase No", artist: "Mohsen Chavoshi" },
      // { name: "Zahed", artist: "Mohsen Chavoshi" },
      // { name: "Deltangi", artist: "Mohsen Chavoshi" },
      // { name: "Naaz", artist: "Mohsen Chavoshi" },
      // { name: "Desire", artist: "Mohsen Chavoshi" },
    ],
  },
];

export const favourites = {
  [FAVOURITE_TYPES.SONG.ARTISTS]: favouriteArtists,
  [FAVOURITE_TYPES.SONG.PLAYLISTS]: favouritePlaylists,
};

export const blogs = [
  {
    _id: 1,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "slug-1",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 2,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-2",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 3,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-3",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 4,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-4",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 5,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-5",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 6,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-6",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 7,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/office-computer-keyboard.jpg",
    body: "",
    publishedAt: "2021-11-11",
    readingTime: "",
    slug: "slug-7",
    category: "Styling",
    minutesToRead: 10,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 8,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-2.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-8",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 9,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-1.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-9",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 10,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/digital-tablet.jpg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-10",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 11,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-3.jfif",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-11",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
  {
    _id: 12,
    title:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam",
    views: "100",
    image: "/images/posts/blog-4.jpeg",
    body: "",
    publishedAt: "",
    readingTime: "",
    slug: "slug-12",
    category: "Styling",
    minutesToRead: 12,
    summary:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dignissimos officiis totam dicta molestiae quibusdam omnis eaque doloribus eos incidunt deserunt!",
  },
];

export const projectsData = {
  en: [
    {
      _id: 0,
      name: "Music",
      link: "https://www.music.ir",
      logo: "/images/projects/music/logo.png",
      medias: [
        {
          src: "/images/projects/music/desktop/1.png",
          title: "Home page fully customizable by admins",
        },
        { src: "/images/projects/music/desktop/2.png", title: "Track page" },
        { src: "/images/projects/music/desktop/3.png", title: "image 3" },
        { src: "/images/projects/music/desktop/4.png", title: "image 4" },
        { src: "/images/projects/music/desktop/5.png", title: "image 5" },
        { src: "/images/projects/music/desktop/6.png", title: "image 6" },
        { src: "/images/projects/music/desktop/7.png", title: "image 7" },
        { src: "/images/projects/music/desktop/8.png", title: "image 8" },
        { src: "/images/projects/music/pwa/1.png", title: "image 1" },
        { src: "/images/projects/music/pwa/2.png", title: "image 2" },
        { src: "/images/projects/music/pwa/3.png", title: "image 3" },
        { src: "/images/projects/music/pwa/4.png", title: "image 4" },
        { src: "/images/projects/music/pwa/5.png", title: "image 5" },
        { src: "/images/projects/music/pwa/6.png", title: "image 6" },
        { src: "/images/projects/music/pwa/7.png", title: "image 7" },
        { src: "/images/projects/music/pwa/8.png", title: "image 8" },
        {
          src: "/images/projects/music/pwa/7-skeleton.png",
          title: "image 7 skeleton",
        },
        {
          src: "/images/projects/music/desktop/1-blur.png",
          title: "image 1 blur",
        },
        {
          src: "/images/projects/music/desktop/1-skeleton.png",
          title: "image 1 skeleton",
        },
        {
          src: "/images/projects/music/desktop/4-skeleton.png",
          title: "image 4 skeleton",
        },
        {
          src: "/images/projects/music/pwa/1-skeleton.png",
          title: "image 1 skeleton",
        },
      ],
      date: "",
      slug: "music",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "Next.js", link: "www.npmjs.com/package/next-seo" },
        { name: "swr", link: "www.npmjs.com/package/swr" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "Redux Saga", link: "www.npmjs.com/package/next-seo" },
        { name: "express", link: "www.npmjs.com/package/next-seo" },
        { name: "socket.io-client", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
      ],
      description: "Persian music streaming platform",
      points: [
        "Super fast page load with incremental static regeneration ( ISR )",
        {
          title: "Extra client-server transport layer with http proxy",
          points: [
            "Saving authorization token as an http-only cookie",
            "Pass every api through the http proxy and adding token to header",
            "This way accessing token is a lot harder for malicious users (not impossible ofcourse)",
            {
              title:
                "This method makes it possible to do more interesting and useful stuffs like : ",
              points: [
                "Hiding An IP Address",
                "Filtering Requests",
                "Protection And Security",
                "etc.",
              ],
            },
          ],
        },
        {
          title: "Multi-language and multi-theme infrastructure",
          points: [
            "SEO first multi language website",
            "Multi directional server side rendered website",
            "No flash theme change",
            "Define custom themes",
          ],
        },
        "Data revalidation intervals on client-side",
        {
          title: "Client side caching",
          points: [
            "Cache first - Network fallback strategy for layout, fonts, logos, avatar and other important data",
            "Reading important data from cache and if failed fallback to network",
            "Rendering a no network connection for completely disabled network connection cases",
          ],
        },
        {
          title: "Considering SEO best practices",
          points: [
            "Optimizing meta tags",
            "Defining canonical tags to Avoid duplicate content",
            "Adding schema tag ( rich result ) for medias, breadcrumbs, ...",
          ],
        },
        {
          title:
            "Faster and more user friendly image load with image optimization method",
          points: [
            "Loading images based on dimensions of image and saving a lot of data and time",
            "Showing blured version of image at first to make waiting for larger images a lot more pleasent",
            "Showimg shimmer animation for unknown images that can't be blured",
          ],
        },
        "Secure coding with front-end security checks",
      ],
    },
    {
      _id: 1,
      name: "Uneed",
      link: ["https://www.uneed.ir", "https://www.merchant.uneed.ir"],
      logo: "/images/projects/uneed/logo.png",
      medias: [
        { src: "/images/projects/uneed/desktop/1.png", title: "image 1" },
        { src: "/images/projects/uneed/desktop/2.png", title: "image 2" },
        { src: "/images/projects/uneed/desktop/3.png", title: "image 3" },
        { src: "/images/projects/uneed/desktop/4.png", title: "image 4" },
        { src: "/images/projects/uneed/desktop/5.png", title: "image 5" },
        { src: "/images/projects/uneed/desktop/6.png", title: "image 6" },
        { src: "/images/projects/uneed/desktop/7.png", title: "image 7" },
        { src: "/images/projects/uneed/desktop/8.png", title: "image 8" },
        { src: "/images/projects/uneed/desktop/9.png", title: "image 9" },
        { src: "/images/projects/uneed/mobile/1.png", title: "image 1" },
      ],
      date: "2020",
      slug: "uneed",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "Next.js", link: "www.npmjs.com/package/next-seo" },
        { name: "Redux Saga", link: "www.npmjs.com/package/next-seo" },
        { name: "express", link: "www.npmjs.com/package/next-seo" },
        { name: "socket.io-client", link: "www.npmjs.com/package/next-seo" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
      ],
      description:
        "A platform for free posting of advertisements and inquiries regarding the purchase and sale of new and used products.",
      points: [
        "Using Next.js framework for server-side rendering",
        "Following Micro Frontend principles",
        "Localization and Internationalization",
        "Using redux saga as a redux async middleware",
      ],
    },
    {
      _id: 2,
      name: "Tarinoo",
      link: [
        "https://www.tarinoo.ir",
        "https://www.zarco.ir",
        "https://www.lapert.ir",
        "https://risu.ir",
        "...",
      ],
      logo: "/images/projects/tarinoo/logo.jpeg",
      medias: [
        { src: "/images/projects/tarinoo/1.png", title: "image 1" },
        { src: "/images/projects/tarinoo/2.png", title: "image 2" },
        { src: "/images/projects/tarinoo/3.png", title: "image 3" },
        { src: "/images/projects/tarinoo/4.png", title: "image 4" },
        { src: "/images/projects/tarinoo/5.png", title: "image 5" },
        { src: "/images/projects/tarinoo/6.png", title: "image 6" },
        { src: "/images/projects/tarinoo/7.png", title: "image 7" },
        { src: "/images/projects/tarinoo/8.png", title: "image 8" },
        { src: "/images/projects/tarinoo/9.png", title: "image 9" },
        { src: "/images/projects/tarinoo/10.png", title: "image 10" },
        { src: "/images/projects/tarinoo/11.png", title: "image 11" },
      ],
      date: "2020",
      slug: "tarinoo",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "Next.js", link: "www.npmjs.com/package/next-seo" },
        { name: "Redux Saga", link: "www.npmjs.com/package/next-seo" },
        { name: "express", link: "www.npmjs.com/package/next-seo" },
        { name: "socket.io-client", link: "www.npmjs.com/package/next-seo" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
      ],
      description:
        "Another product of uneed infrastructure, built to sell fully customized websites to business-type users",
      points: [
        "writing code once and using it in other sites",
        "full control over products, banners, contents and ...",
      ],
    },
    {
      _id: 3,
      name: "Bityon",
      link: "",
      logo: "/images/projects/bityon/logo.png",
      medias: [
        { src: "/images/projects/bityon/desktop/1.png", title: "image 1" },
        { src: "/images/projects/bityon/desktop/2.png", title: "image 2" },
        { src: "/images/projects/bityon/desktop/3.png", title: "image 3" },
        { src: "/images/projects/bityon/desktop/4.png", title: "image 4" },
        { src: "/images/projects/bityon/desktop/5.png", title: "image 5" },
        { src: "/images/projects/bityon/desktop/6.png", title: "image 6" },
        { src: "/images/projects/bityon/desktop/7.png", title: "image 7" },
        { src: "/images/projects/bityon/mobile/1.png", title: "image 1" },
        { src: "/images/projects/bityon/mobile/2.png", title: "image 2" },
        { src: "/images/projects/bityon/mobile/3.png", title: "image 3" },
        { src: "/images/projects/bityon/mobile/4.png", title: "image 4" },
      ],
      date: "",
      slug: "bityon",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "Next.js", link: "www.npmjs.com/package/next-seo" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
        { name: "highcharts", link: "www.npmjs.com/package/highcharts" },
      ],
      description:
        "Customer relationship management panel that provides an all-in-one social media managemnt service.",
      points: [
        {
          title: "Multi-language and multi-theme infrastructure",
          points: [
            "SEO first multi language website",
            "Multi directional server side rendered website",
            "No flash theme change",
            "Define custom themes",
          ],
        },
      ],
    },
    {
      _id: 4,
      name: "BIZ",
      link: "https://www.bizmlm.ir",
      logo: "/images/projects/biz/logo.png",
      medias: [
        { src: "/images/projects/biz/1.png", title: "image 1" },
        { src: "/images/projects/biz/2.png", title: "image 2" },
        { src: "/images/projects/biz/3.png", title: "image 3" },
        { src: "/images/projects/biz/4.png", title: "image 4" },
        { src: "/images/projects/biz/5.png", title: "image 5" },
        { src: "/images/projects/biz/6.png", title: "image 6" },
        { src: "/images/projects/biz/7.png", title: "image 7" },
        { src: "/images/projects/biz/8.png", title: "image 8" },
      ],
      date: "",
      slug: "biz",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "socket.io-client", link: "www.npmjs.com/package/next-seo" },
        { name: "React Query", link: "www.npmjs.com/package/next-seo" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
      ],
      description: "The biggest iranian network marketing company",
      points: [
        {
          title: "Custom SSR implementation",
          points: [
            "manual server-side rendering with express",
            "both server and client redux support with synced isomorphic redux state",
            "ssr data prefetching and passing it to pages as props",
          ],
        },
        "caching requests with Redis key-value pair database",
        "notifications with firebase",
      ],
    },
    {
      _id: 5,
      name: "CRM Panel",
      link: "https://www.crm.ir",
      logo: "/images/projects/crm/logo.png",
      medias: [
        { src: "/images/projects/crm/1.png", title: "image 1" },
        { src: "/images/projects/crm/2.png", title: "image 2" },
        { src: "/images/projects/crm/3.png", title: "image 3" },
        { src: "/images/projects/crm/4.png", title: "image 4" },
      ],
      date: "",
      slug: "crm",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "socket.io-client", link: "www.npmjs.com/package/next-seo" },
        { name: "React Query", link: "www.npmjs.com/package/next-seo" },
        { name: "Styled Components", link: "www.npmjs.com/package/next-seo" },
        { name: "i18next", link: "www.npmjs.com/package/next-seo" },
      ],
      description:
        "Customer relationship management panel that provides an all-in-one social media managemnt tool.",
      points: [
        {
          title: "Using socket.io for real-time communication with server",
          points: [
            "using socket.io-client along with context api",
            "building a custom useChat hook for a cleaner way to connect components to communicate with realtime updating state",
          ],
        },
        "writing simple end to end tests with cypress",
        "connecting to Telegram, WhatsApp, Instagram accounts",
      ],
    },
    {
      _id: 6,
      name: "And so forth ...",
      logo: "/images/projects/etc.png",
      data: "2018-present",
      description: "Projects that I'm not really proud of ( ^_^;)",
      techs: [
        { name: "React", link: "www.npmjs.com/package/next-seo" },
        { name: "React-native", link: "www.npmjs.com/package/next-seo" },
        { name: "Angular", link: "www.npmjs.com/package/next-seo" },
        { name: "wordpress", link: "www.npmjs.com/package/next-seo" },
      ],
    },
  ],
};
